layout_spectrum: 0.26916548050940037
typography_spectrum: 0.2962125185877085
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.625210513593629
  lightness: 0.4080008650198579
  saturation: 0.22273088968358934
  rhythmicContrast: 0.7049022542778403
name: Best James
favicon: null
title: Joseph Best-James
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
