typography_spectrum: 0.2962125185877085
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.625210513593629
  lightness: 0.4080008650198579
  saturation: 0.22273088968358934
  rhythmicContrast: 0.7049022542778403
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.26916548050940037
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/a990ed49-b750-4442-8777-fead3fdf5519.jpg
name: Best James
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: LinkedIn
    url: 'https://www.linkedin.com/in/josephbestjames'
    type: external
  - name: Twitter
    url: 'https://twitter.com/JosephBestJames'
    type: external
favicon: null
title: Joseph Best-James
purpose: []
